### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by chrzrdx** [sorokya/reoserv.net#4]
Adding a `filter: invert(1)` to the html tag already gives a pretty nice dark mode look to the site (but screws up the images)

![image](https://github.com/sorokya/reoserv.net/assets/17521606/41f57948-1633-4a85-8579-c6c4d37aa695)

We can try and keep the same aesthetic for dark mode. 

Instead of building out a full theme switcher, we could try and build out dark mode to just respect the user's media preference. And then later on add a theme switch button at the top.

**Comment by sorokya** [comment]
I was thinking of just inverting the background image and swapping darks with lights on text. Looks good except the logo yeah.

I didn't even know invert was a css thing lol
